## -*- mode:ulam -*-
#=t41030_test_compiler_element_classreffuncreturnvalue_fail
##
## gen error:
## include/Ue_10133Foo10.tcc:79: FAILED: UNRETURNABLE_REFERENCE
##
#!
Exit status: -1
Ue_Foo { Int(3) m_i(3);  Int test() {  Foo f3;  f3 m_i . 1 cast = Foo& r = self ( f3 cast )caller2 .;  r m_i . cast return } }
##
## informed by Dave email 2/10/2017 and t41029, see safe/t41032
##
#>Foo.ulam
  ulam 3;
element Foo
{
  Int(3) m_i = 3;

  Foo & func(Foo& arg1, Foo& arg2)
  {
    if(arg1.m_i == 3)
      return arg1;
    return arg2;
  }

  Void caller1()
  {
    Foo f1;
    caller2(f1);
  }

  Foo & caller2(Foo& a1)
  {
    Foo f2;
    Foo & r2 = f2;
    return func(r2, a1);  // Safe or not?  Can't know til runtime.
  }

  Int test() {
    Foo f3;
    f3.m_i = 1;
    Foo & r = caller2(f3);
    return r.m_i;
  }
}

#.
